// BTC TBTC RBTC TRBTC RIF TRIF
import { networks } from 'bitcoinjs-lib';
import references from '../../assets/references';
import { ASSETS_CONTRACT } from '../constants';

const coinType = {
  BTC: {
    networkId: 0,
    coinType: 0,
    network: networks.bitcoin,
    icon: references.images.BTC,
    defaultName: 'Bitcoin',
    chain: 'Bitcoin',
    type: 'Mainnet',
    symbol: 'BTC',
  },
  RBTC: {
    networkId: 30,
    coinType: 137,
    icon: references.images.RBTC,
    defaultName: 'Smart Bitcoin',
    chain: 'Rootstock',
    type: 'Mainnet',
    symbol: 'RBTC',
  },
  RIF: {
    networkId: 30,
    coinType: 137,
    icon: references.images.RIF,
    defaultName: 'RSK Infra Framework',
    chain: 'Rootstock',
    type: 'Mainnet',
    symbol: 'RIF',
    contractAddress: ASSETS_CONTRACT.RIF.Mainnet,
  },
  DOC: {
    networkId: 30,
    coinType: 137,
    icon: references.images.DOC,
    defaultName: 'Dollar on Chain',
    chain: 'Rootstock',
    type: 'Mainnet',
    symbol: 'DOC',
    contractAddress: ASSETS_CONTRACT.DOC.Mainnet,
  },
  RIFP: {
    networkId: 30,
    coinType: 137,
    icon: references.images.RIFP,
    defaultName: 'RIFPro',
    chain: 'Rootstock',
    type: 'Mainnet',
    symbol: 'RIFP',
    contractAddress: ASSETS_CONTRACT.RIFP.Mainnet,
  },
  RDOC: {
    networkId: 30,
    coinType: 137,
    icon: references.images.RDOC,
    defaultName: 'RIF Dollar on Chain',
    chain: 'Rootstock',
    type: 'Mainnet',
    symbol: 'RDOC',
    contractAddress: ASSETS_CONTRACT.RDOC.Mainnet,
  },
  BITP: {
    networkId: 30,
    coinType: 137,
    icon: references.images.BITP,
    defaultName: 'BitPRO',
    chain: 'Rootstock',
    type: 'Mainnet',
    symbol: 'BITP',
    contractAddress: ASSETS_CONTRACT.BITP.Mainnet,
  },
  CustomToken: {
    networkId: 30,
    coinType: 137,
    icon: references.images.customToken,
    chain: 'Rootstock',
    type: 'Mainnet',
  },
  BTCTestnet: {
    networkId: 1,
    coinType: 1,
    network: networks.testnet,
    icon: references.images.BTC_GREY,
    defaultName: 'Bitcoin',
    chain: 'Bitcoin',
    type: 'Testnet',
    symbol: 'BTC',
  },
  RBTCTestnet: {
    networkId: 31,
    coinType: 37310,
    icon: references.images.RBTC_GREY,
    defaultName: 'Smart Bitcoin',
    chain: 'Rootstock',
    type: 'Testnet',
    symbol: 'RBTC',
  },
  RIFTestnet: {
    networkId: 31,
    coinType: 37310,
    icon: references.images.RIF_GREY,
    defaultName: 'RSK Infra Framework',
    chain: 'Rootstock',
    type: 'Testnet',
    symbol: 'RIF',
    contractAddress: ASSETS_CONTRACT.RIF.Testnet,
  },
  DOCTestnet: {
    networkId: 31,
    coinType: 37310,
    icon: references.images.DOC_GREY,
    defaultName: 'Dollar on Chain',
    chain: 'Rootstock',
    type: 'Testnet',
    symbol: 'DOC',
    contractAddress: ASSETS_CONTRACT.DOC.Testnet,
  },
  RIFPTestnet: {
    networkId: 31,
    coinType: 37310,
    icon: references.images.RIFP_GREY,
    defaultName: 'RIFPro',
    chain: 'Rootstock',
    type: 'Testnet',
    symbol: 'RIFP',
    contractAddress: ASSETS_CONTRACT.RIFP.Testnet,
  },
  RDOCTestnet: {
    networkId: 31,
    coinType: 37310,
    icon: references.images.RDOC_GREY,
    defaultName: 'RIF Dollar on Chain',
    chain: 'Rootstock',
    type: 'Testnet',
    symbol: 'RDOC',
    contractAddress: ASSETS_CONTRACT.RDOC.Testnet,
  },
  BITPTestnet: {
    networkId: 31,
    coinType: 37310,
    icon: references.images.BITP_GREY,
    defaultName: 'BitPRO',
    chain: 'Rootstock',
    type: 'Testnet',
    symbol: 'BITP',
    contractAddress: ASSETS_CONTRACT.BITP.Testnet,
  },
  CustomTokenTestnet: {
    networkId: 31,
    coinType: 37310,
    icon: references.images.customToken_grey,
    chain: 'Rootstock',
    type: 'Testnet',
  },
};

export default coinType;
