// BTC TBTC RBTC TRBTC RIF TRIF
import { networks } from 'bitcoinjs-lib';
import references from '../../assets/references';

const coinType = {
  BTC: {
    networkId: 0,
    pathNetworkId: 0,
    network: networks.bitcoin,
    icon: references.images.BTC,
    defaultName: 'Bitcoin',
    chain: 'Bitcoin',
    type: 'Mainnet',
    symbol: 'BTC',
  },
  RBTC: {
    networkId: 30,
    pathNetworkId: 137,
    icon: references.images.RBTC,
    defaultName: 'Smart Bitcoin',
    chain: 'Rootstock',
    type: 'Mainnet',
    symbol: 'RBTC',
  },
  RIF: {
    networkId: 30,
    pathNetworkId: 137,
    icon: references.images.RIF,
    defaultName: 'RSK Infra Framework',
    chain: 'Rootstock',
    type: 'Mainnet',
    symbol: 'RIF',
  },
  DOC: {
    networkId: 30,
    pathNetworkId: 137,
    icon: references.images.DOC,
    defaultName: 'Dollar on Chain',
    chain: 'Rootstock',
    type: 'Mainnet',
    symbol: 'DOC',
  },
  RIFP: {
    networkId: 30,
    pathNetworkId: 137,
    icon: references.images.RIFP,
    defaultName: 'RIFPro',
    chain: 'Rootstock',
    type: 'Mainnet',
    symbol: 'RIFP',
  },
  RDOC: {
    networkId: 30,
    pathNetworkId: 137,
    icon: references.images.RDOC,
    defaultName: 'RIF Dollar on Chain',
    chain: 'Rootstock',
    type: 'Mainnet',
    symbol: 'RDOC',
  },
  BTCTestnet: {
    networkId: 1,
    pathNetworkId: 1,
    network: networks.testnet,
    icon: references.images.BTC_GREY,
    defaultName: 'Bitcoin',
    chain: 'Bitcoin',
    type: 'Testnet',
    symbol: 'BTC',
  },
  RBTCTestnet: {
    networkId: 31,
    pathNetworkId: 37310,
    icon: references.images.RBTC_GREY,
    defaultName: 'Smart Bitcoin',
    chain: 'Rootstock',
    type: 'Testnet',
    symbol: 'RBTC',
  },
  RIFTestnet: {
    networkId: 31,
    pathNetworkId: 37310,
    icon: references.images.RIF_GREY,
    defaultName: 'RSK Infra Framework',
    chain: 'Rootstock',
    type: 'Testnet',
    symbol: 'RIF',
  },
  DOCTestnet: {
    networkId: 31,
    pathNetworkId: 37310,
    icon: references.images.DOC_GREY,
    defaultName: 'Dollar on Chain',
    chain: 'Rootstock',
    type: 'Testnet',
    symbol: 'DOC',
  },
  RIFPTestnet: {
    networkId: 31,
    pathNetworkId: 137,
    icon: references.images.RIFP_GREY,
    defaultName: 'RIFPro',
    chain: 'Rootstock',
    type: 'Testnet',
    symbol: 'RIFP',
  },
  RDOCTestnet: {
    networkId: 31,
    pathNetworkId: 137,
    icon: references.images.RDOC_GREY,
    defaultName: 'RIF Dollar on Chain',
    chain: 'Rootstock',
    type: 'Testnet',
    symbol: 'RDOC',
  },
  CustomToken: {
    networkId: 31,
    pathNetworkId: 137,
    icon: references.images.customToken,
    chain: 'Rootstock',
    type: 'Mainnet',
  },
  CustomTokenTestnet: {
    networkId: 31,
    pathNetworkId: 37310,
    icon: references.images.customToken_grey,
    chain: 'Rootstock',
    type: 'Testnet',
  },
};

export default coinType;
