export enum ErrorCode {
    ERROR_NOT_IMPLEMENTED = 'ERROR_NOT_IMPLEMENTED',
    ERROR_GENERIC = 'ERROR_GENERIC',
    ERROR_INTERNAL = 'ERROR_INTERNAL',
    ERROR_UNKNOWN_NETWORK = 'ERROR_UNKNOWN_NETWORK',
    ERROR_WALLET_NOT_FOUND = 'ERROR_WALLET_NOT_FOUND',
    ERROR_VALUE_NOT_FOUND = 'ERROR_VALUE_NOT_FOUND',
    ERROR_CANT_RESTORE_WALLET = 'ERROR_CANT_RESTORE_WALLET',
    ERROR_OVERFLOW = 'ERROR_OVERFLOW',
    ERROR_INSUFFICIENT_FUNDS = 'ERROR_INSUFFICIENT_FUNDS',
    ERROR_UNSUPPORTED_CURRENCY = 'ERROR_UNSUPPORTED_CURRENCY',
    ERROR_PRIVATE_KEY_NOT_FOUND = 'ERROR_PRIVATE_KEY_NOT_FOUND'
}
