const onBoardingStepEnum = {
  SELECTED_FLOW: 'SELECTED_FLOW',
  PIN_CREATED: 'PIN_CREATED',
  CREATED_WALLET: 'CREATED_WALLET',
  IMPORTED_WALLET: 'IMPORTED_WALLET',
  PHRASE_VERIFIED: 'PHRASE_VERIFIED',
  ON_COMPLETED: 'ON_COMPLETED',
};

export default onBoardingStepEnum;
